services:
  database:
    container_name: api-server-todo.flycast
    image: postgres:15.10
    volumes:
      - ~/todo/data:/data/db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  api:
    container_name: todo_api
    build:
      context: ../../
      dockerfile: ./server/todo/Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - database
    environment:
      - DB_URL=${DB_URL}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - TOKEN_DURATION=${TOKEN_DURATION}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - REFRESH_TOKEN_DURATION=${REFRESH_TOKEN_DURATION}
      - SERVER_PORT=${SERVER_PORT}
