# fly.toml app configuration file generated for api-server-todo on 2024-12-27T20:08:54+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-server-todo'
primary_region = 'nrt'

[build]
dockerfile = 'Dockerfile'

[http_service]
internal_port = 3001
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
